* Passing on Magit for now
  _Friday, December 29th, 2017._

  First of all, can we just assume free text like this (that is, text that's inside a heading, but not one itself or not any other kind of data) is Markdown?

  I miss the easy code blocks with 4 spaces and backticks, and googling org mode code block just scared the shit out of me.

  I'm sure there are a bunch of keybindings to make the pill easier to swallow, but the bare syntax just looks like a lot of typing, and hard on the eyes.

** Back to Bash

   I figured out the basic Magit commands, squeezed a commit out, and managed to push it to Github. But boy was that clunky.

   I'm especially disfond of what I could make the `git log` equivalent churn out. For some reason the diff lines were cut off at around 60% width.

   Plus, +I hadn't set up `evil-magit`+, so I kept spitting out unwanted commands whilst trying to navigate text, it was a mess. (I later found out that the =git= layer includes =evil-magit=, but I managed to make a mess anyway. On a happier note, I found out that `=` replaces backticks for inline code formatting.)

   It's also hard to compete with my terminal-based git-fu, with all my beautiful auto-completed git aliases. Check this out!:

    alias ga='git add'
    alias gb='git branch'
    alias gba='git branch -a'
    alias gc='git checkout'
    alias gd='git diff -w'
    alias gf='git fetch'
    alias gi='git diff -w --staged'
    alias gl='git log --stat'
    alias glp='git log --stat -p'
    alias gm='git merge'
    alias gp='git push'
    alias gpl='git pull'
    alias gs='git status'
    alias gt='git stash'
    alias gta='git stash apply'

   Now pair that with [[https://superuser.com/a/437508][this amazing bash script]] that adds completion to aliases, and you've got a killer combo. This stuff is welded into my fingers.

   So for now I'll take a step back and learn how drop iTerm2 in favor of some Emacs terminal first, _then_ start dragging in what makes sense.
* Hello Org Log
  _Thursday, December 28th, 2017._

  So this is me trying to learn how to blog some links with commentary without
  leaving Emacs.

  When I say Emacs from now on I mean "my l33t h4x0r Remacs HEAD +
  Spacemacs@develop super duper setup."

  What that really means is that I'm a n00b who didn't want to start with
  "vanilla" Emacs and spend the next year setting it up, and just went with the
  "batteries included" approach.

  It seems like Spacemacs is the Ubuntu of Emacs, and I'm all for (K|)Ubuntus.

  Now, building Remacs and switching to the develop branch of Spacemacs was so
  breezeful and piece-of-cakely that it barely counts towards my street credit
  score. It does hugely towards their developers' though.

  Thank you, Wilfred Hughes, Sylvian Benner, et al. 🙏

** One Org File
   What I know about org-mode so far is that it's a tree of stuff. That's about
   it.

   So for now this log will be a single org file that I'll push to Github (much
   to the chagrin of whom's name I'm deliberately not camel-caseing).

   The single org-file structure seems to have worked pretty well for [[http://endlessparentheses.com/how-i-blog-one-year-of-posts-in-a-single-org-file.html][Mr.
   Malabarba]], so let's start there.

   Of course, his setup is light-years ahead of anything I could dream of coming
   up with, but hey, gotta start somewhere.

   Github automatically adds `#` links to headings, so each post gets its own URL. This is the simplest Org blog that could possibly work.

** TODOs
   What's an Org file without a bunch of TODOs?

*** DONE Figure out how to commit and push from within Emacs (no idea how to use Magit yet.)
    CLOSED: [2017-12-29 Fri 11:25]
*** TODO Figure out how to display and input emojis on Emacs.
    Seriously, this is not built in?? Where are your priorities, people? 🤨
*** TODO Figure out how to properly timestamp org-mode headings.
** Links
*** https://github.com/Wilfred/remacs
    Give Remacs a try, you've got nothing to lose!

    It's super easy to set up, won't break your Spacemacs, tracks the Emacs repo
    so you're always up to date, and... it's like Servo, but for Emacs, right?
    Gotta be good.
*** http://sachachua.com/emacs-news
    Good recap on the current weekly events in Emacs world. Also includes
    Spacemacs links. Lots of advanced stuff, but nice for getting up to speed
    with the community side of things.
